version: "3.9"

services:
  app:
    build: .
    container_name: crud_app

    ports:
      - "8080:80"

    volumes:
      - .:/var/www/html

    depends_on:
      - db

    restart: always

  db:
    image: mysql:8.0
    container_name: crud_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: barang_db

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crud_phpmyadmin

    restart: always

    depends_on:
      - db

    ports:
      - "8081:80"

    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password

volumes:
  mysql_data: